artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  source_urls:
    books: "https://github.com/Jimster397/Book-recommender-system-collab-filtering/releases/download/v1.0/BX-Books.csv"
    ratings: "https://github.com/Jimster397/Book-recommender-system-collab-filtering/releases/download/v1.0/BX-Book-Ratings.csv"
    users: "https://github.com/Jimster397/Book-recommender-system-collab-filtering/releases/download/v1.0/BX-Users.csv"
  
  root_dir: artifacts/data_ingestion
  local_data_dir: artifacts/data_ingestion/dataset
  raw_data_dir: artifacts/data_ingestion/raw_data
  ingested_dir: artifacts/data_ingestion/ingested_data


data_validation_config:
  clean_data_dir: clean_data
  serialized_objects_dir: serialized_objects
  books_csv_file: BX-Books.csv
  ratings_csv_file: BX-Book-Ratings.csv
  users_csv_file: BX-Users.csv