artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  source_urls:
    books: "https://github.com/Jimster397/Book-recommender-system-collab-filtering/releases/download/v1.0/BX-Books.csv"
    ratings: "https://github.com/Jimster397/Book-recommender-system-collab-filtering/releases/download/v1.0/BX-Book-Ratings.csv"
    users: "https://github.com/Jimster397/Book-recommender-system-collab-filtering/releases/download/v1.0/BX-Users.csv"
  raw_data_dir: artifacts/data_ingestion/raw_data


data_validation_config:
  clean_data_dir: clean_data
  serialized_objects_dir: serialized_objects
  books_csv_file: BX-Books.csv
  ratings_csv_file: BX-Book-Ratings.csv
  users_csv_file: BX-Users.csv


data_transformation_config:
  transformed_data_dir: transformed_data


model_trainer_config:
  trained_model_dir: trained_model
  trained_model_name: model.pkl


recommendation_config:
  poster_api_url: https://api.themoviedb.org/3/movie/{}?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US


evaluation_config:
 evaluation_output: evaluation_output