artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  source_urls:
    books: "https://github.com/Jimster397/Book-recommender-system-collab-filtering/releases/download/v1.0/BX-Books.csv"
    ratings: "https://github.com/Jimster397/Book-recommender-system-collab-filtering/releases/download/v1.0/BX-Ratings.csv"
    users: "https://github.com/Jimster397/Book-recommender-system-collab-filtering/releases/download/v1.0/BX-Users.csv"
  
  root_dir: artifacts/data_ingestion
  local_data_dir: artifacts/data_ingestion/dataset
  raw_data_dir: artifacts/data_ingestion/raw_data
  ingested_dir: artifacts/data_ingestion/ingested_data